authors:
  myyerrol:
    name: 缪宇飏
    description: 开源IP/SoC工程师
    avatar: https://github.com/myyerrol.png
    url: https://github.com/myyerrol
  XuLiDa1:
    name: 许立达
    description: 开源SoC/后端工程师
    avatar: https://github.com/XuLiDa1.png
    url: https://github.com/XuLiDa1
  zhaoxueyan1:
    name: 赵雪岩
    description: 开源EDA博士生
    avatar: https://github.com/zhaoxueyan1.png
    url: https://github.com/zhaoxueyan1
