authors:
  myyerrol:
    name: 缪宇飏
    description: 开源IP/SoC、嵌入式工程师
    avatar: https://github.com/myyerrol.png
    url: https://github.com/myyerrol
  XuLiDa1:
    name: 许立达
    description: 开源SoC、后端工程师
    avatar: https://github.com/XuLiDa1.png
    url: https://github.com/XuLiDa1
  zhaoxueyan1:
    name: 赵雪岩
    description: 开源EDA博士生
    avatar: https://github.com/zhaoxueyan1.png
    url: https://github.com/zhaoxueyan1
  puckbee:
    name: 解壁伟
    description: 团队负责人
    avatar: https://github.com/puckbee.png
    url: https://github.com/puckbee
  xiaokesu:
    name: 苏小可
    description: “一生一芯”负责人
    avatar: https://github.com/xiaokesu.png
    url: https://github.com/xiaokesu
  SZTUChips:
    name: 杨昊天
    description: “一生一芯”助教
    avatar: https://github.com/SZTUChips.png
    url: https://github.com/SZTUChips
  O5order:
    name: 许鹏远
    description: “一生一芯”助教
    avatar: https://github.com/O5order.png
    url: https://github.com/O5order
  next-zeta:
    name: 陈炫君
    description: “一生一芯”助教
    avatar: https://github.com/next-zeta.png
    url: https://github.com/next-zeta
  OSCPU:
    name: OSCPU
    description: “一生一芯”团队
    avatar: https://github.com/OSCPU.png
    url: https://github.com/OSCPU
