authors:
  myyerrol:
    name: Yuyang Miao
    description: Open Source IP / SoC Engineer
    avatar: https://github.com/myyerrol.png
    url: https://github.com/myyerrol
  XuLiDa1:
    name: Lida Xu
    description: Open Source SoC / Backend Engineer
    avatar: https://github.com/XuLiDa1.png
    url: https://github.com/XuLiDa1
  zhaoxueyan1:
    name: Xueyan Zhao
    description: Open Source EDA PhD
    avatar: https://github.com/zhaoxueyan1.png
    url: https://github.com/zhaoxueyan1
